trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '12-CI-CD-Pipelines/Azure-Devops/AKS'
    commandOptions: '-var="Name=$(Name)" -var="resourceGroup=$(resourceGroup)" -var="clientID=$(clientID)" -var="clientSecret=$(clientSecret)" -var="location=$(location)"'
    backendServiceArm: 'vidyacluster (42cbaa9e-4e8c-4cba-9ae9-91d031b0f15d)'
    backendAzureRmResourceGroupName: 'Dev10'
    backendAzureRmStorageAccountName: 'cloudskillstfstate92'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'tf/terraform.tfstate'

- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '12-CI-CD-Pipelines/Azure-Devops/AKS'
    commandOptions: '-var="Name=$(Name)" -var="resourceGroup=$(resourceGroup)" -var="clientID=$(clientID)" -var="clientSecret=$(clientSecret)" -var="location=$(location)"'
    environmentServiceNameAzureRM: 'vidyacluster (42cbaa9e-4e8c-4cba-9ae9-91d031b0f15d)'
